# -*- coding: utf-8 -*-
"""data_fetcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S3gXoJfLLeIAe5Lsuap3Z9hu-wlaT7F9
"""

import numpy as np
import pandas as pd
import os
import time
import requests

api_key = "_"

train_csv = "train.csv"
test_csv= "test.csv"

train_img_dir = "images_train"
test_img_dir = "images_test"

img_size = "400x400"
zoom = 17
map = "satellite"

delay = 0.2

os.makedirs(train_img_dir, exist_ok=True)
os.makedirs(test_img_dir, exist_ok=True)

def download_image(lat, lon, save_path):
    url = (
        "https://maps.googleapis.com/maps/api/staticmap"
        f"?center={lat},{lon}"
        f"&zoom={zoom}"
        f"&size={img_size}"
        f"&maptype={map}"
        f"&key={api_key}"
    )

    response = requests.get(url)

    if response.status_code == 200:
        with open(save_path, "wb") as f:
            f.write(response.content)
        return True
    else:
        return False

def process_dataset(csv_path, image_dir):
    df = pd.read_csv(csv_path)

    for _, row in df.iterrows():
        img_name = f"{row['id']}.png"
        img_path = os.path.join(image_dir, img_name)

        if os.path.exists(img_path):
            continue

        success = download_image(
            lat=row["lat"],
            lon=row["long"],
            save_path=img_path
        )

        time.sleep(delay)

process_dataset(train_csv, train_img_dir)
process_dataset(test_csv, test_img_dir)